name: sistema_erp_cd
description: ERP Unificado - Gerenciamento de pedidos para todas as unidades Ao Gosto Carnes
publish_to: 'none'
version: 1.5.0+150

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.2
  google_fonts: ^6.2.1
  http: ^1.2.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  open_file: ^3.5.9
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  fl_chart: ^0.68.0
  permission_handler: ^11.3.1
  printing: ^5.14.2
  pdf: ^3.11.1
  shared_preferences: ^2.5.2
  url_launcher: ^6.3.0
  crypto: ^3.0.3
  path: ^1.9.0
  package_info_plus: ^8.0.0
  mask_text_input_formatter: ^2.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icon/icon2.png
    - assets/icon/GO-logo.png


windows:
  executable: erp_unificado.exe

flutter_launcher_icons:
  android:
    generate: true
  ios:
    generate: true
  macos:
    generate: true
  windows:
    generate: true
    executable: erp_unificado.exe
  image_path: "assets/icon/GO-logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon2.png"